# Generated by Django 4.0.4 on 2022-04-30 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updateddat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('firstName', models.CharField(max_length=225)),
                ('lastName', models.CharField(max_length=225)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updateddat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('games_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesCoolWebsite.games')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesCoolWebsite.users')),
            ],
        ),
    ]
