# Generated by Django 4.0.4 on 2022-05-02 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joesCoolWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='games_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamescores', to='joesCoolWebsite.games'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userscores', to='joesCoolWebsite.users'),
        ),
    ]
