# Generated by Django 4.0.4 on 2022-05-10 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joesCoolWebsite', '0002_alter_scores_games_id_alter_scores_users_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(max_length=225)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesCoolWebsite.users')),
            ],
        ),
    ]
