# Generated by Django 4.0.4 on 2022-05-10 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joesCoolWebsite', '0003_favgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usersfavgames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesCoolWebsite.games')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joesCoolWebsite.users')),
            ],
        ),
        migrations.RenameField(
            model_name='scores',
            old_name='score',
            new_name='scores',
        ),
        migrations.DeleteModel(
            name='Favgame',
        ),
    ]
