# Generated by Django 4.0.4 on 2022-05-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joesCoolWebsite', '0004_usersfavgames_rename_score_scores_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='usersthatfav',
            field=models.ManyToManyField(related_name='favoritedgames', to='joesCoolWebsite.users'),
        ),
        migrations.DeleteModel(
            name='Usersfavgames',
        ),
    ]
