# Generated by Django 4.0.4 on 2022-05-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joesCoolWebsite', '0005_games_usersthatfav_delete_usersfavgames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='usersthatfav',
            field=models.ManyToManyField(blank=True, related_name='favoritedgames', to='joesCoolWebsite.users'),
        ),
    ]
