# Generated by Django 4.0.4 on 2022-05-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joesCoolWebsite', '0006_alter_games_usersthatfav'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='comments',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
