# Generated by Django 4.0.4 on 2022-05-13 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joesCoolWebsite', '0007_games_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='comments',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=225)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('games_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamecomments', to='joesCoolWebsite.games')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercomments', to='joesCoolWebsite.users')),
            ],
        ),
    ]
